// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtomButton: typeof import('./src/ui/components/atoms/buttons/AtomButton.vue')['default']
    AtomButtonSearch: typeof import('./src/ui/components/atoms/buttons/AtomButtonSearch.vue')['default']
    AtomCircleAvatar: typeof import('./src/ui/components/atoms/avatars/AtomCircleAvatar.vue')['default']
    AtomCircleButton: typeof import('./src/ui/components/atoms/buttons/AtomCircleButton.vue')['default']
    AtomDirection: typeof import('./src/ui/components/atoms/directions/AtomDirection.vue')['default']
    AtomDoubleLabel: typeof import('./src/ui/components/atoms/labels/AtomDoubleLabel.vue')['default']
    AtomDoubleSwitch: typeof import('./src/ui/components/atoms/switches/AtomDoubleSwitch.vue')['default']
    AtomHeaderLink: typeof import('./src/ui/components/atoms/links/AtomHeaderLink.vue')['default']
    AtomInput: typeof import('./src/ui/components/inputs/AtomInput.vue')['default']
    AtomInputFilled: typeof import('./src/ui/components/inputs/AtomInputFilled.vue')['default']
    AtomInputTranslucent: typeof import('./src/ui/components/inputs/AtomInputTranslucent.vue')['default']
    AtomInputTranslusent: typeof import('./src/ui/components/inputs/AtomInputTranslucent.vue')['default']
    AtomLink: typeof import('./src/ui/components/atoms/links/AtomLink.vue')['default']
    AtomSwitch: typeof import('./src/ui/components/atoms/switch/AtomDoubleSwitch.vue')['default']
    AtomTab: typeof import('./src/ui/components/atoms/tabs/AtomTab.vue')['default']
    AtomTabs: typeof import('./src/ui/components/atoms/tabs/AtomTabsSquare.vue')['default']
    AtomTabsRounded: typeof import('./src/ui/components/atoms/tabs/AtomTabsRounded.vue')['default']
    AtomTabsSquare: typeof import('./src/ui/components/atoms/tabs/AtomTabsSquare.vue')['default']
    AtomTag: typeof import('./src/ui/components/atoms/tags/AtomTag.vue')['default']
    MoleculeBlogCard: typeof import('./src/ui/components/molecules/cards/MoleculeBlogCard.vue')['default']
    MoleculeFreeTrialCard: typeof import('./src/ui/components/molecules/cards/MoleculeFreeTrialCard.vue')['default']
    MoleculePriceCard: typeof import('./src/ui/components/molecules/cards/MoleculePriceCard.vue')['default']
    MoleculeReviewCardIn: typeof import('./src/ui/components/molecules/cards/MoleculeReviewCardIn.vue')['default']
    MoleculeReviewCardOut: typeof import('./src/ui/components/molecules/cards/MoleculeReviewCardOut.vue')['default']
    MoleculeServiceCard: typeof import('./src/ui/components/molecules/cards/MoleculeServiceCard.vue')['default']
    MoleculeStarterPriceCard: typeof import('./src/ui/components/molecules/cards/MoleculePriceCard.vue')['default']
    ReviewCard: typeof import('./src/ui/components/molecules/cards/MoleculeReviewCardOut.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/ui/components/molecules/cards/MoleculeServiceCard.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
